version: 2
jobs:
  build-push:
    docker:
      - image: meliuz/docker-deployer:latest
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Docker login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS

      - run:
          name: Docker build image
          command: docker build --tag meliuz/${CIRCLE_PROJECT_REPONAME}:latest .

      - run:
          name: Docker push image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker push meliuz/${CIRCLE_PROJECT_REPONAME}:latest
            fi

workflows:
  version: 2
  meliuz-workflow:
    jobs:
      - build-push:
          context: global
